relative_links:
  enabled: true
  collections: true
include:
  - README.md
plugins:
  - jekyll-remote-theme
remote_theme:
#   pages-themes/cayman@v0.2.0
#   pages-themes/architect@v0.2.0
  pages-themes/merlot@v0.2.0

