relative_links:
  enabled: true
  collections: true
include:
  - README.md
plugins:
  - jekyll-remote-theme
remote_theme:
  pages-themes/architect@v0.2.0
#   pages-themes/cayman@v0.2.0
#   pages-themes/dinky@v0.2.0
#   pages-themes/hacker@v0.2.0
#   pages-themes/leap-day@v0.2.0
#   pages-themes/merlot@v0.2.0
#   pages-themes/midnight@v0.2.0
#DNU     pages-themes/minima@v0.2.0
#   pages-themes/minimal@v0.2.0
#   pages-themes/modernist@v0.2.0
#   pages-themes/slate@v0.2.0
#   pages-themes/tactile@v0.2.0
#   pages-themes/time-machine@v0.2.0
