relative_links:
  enabled: true
  collections: true
include:
  - README.md
# theme: jekyll-theme-cayman
remote_theme: pages-themes/architect@v0.2.0
plugins:
#   - jekyll-relative-links
  - jekyll-remote-theme
